name: dart_solid_principles
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
